# Generated by Django 5.2 on 2025-08-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("match_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("radiant_win", models.BooleanField()),
                ("duration", models.IntegerField()),
                ("start_time", models.IntegerField()),
                ("game_mode", models.IntegerField()),
                ("lobby_type", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMatchStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steam_id", models.BigIntegerField()),
                ("player_slot", models.IntegerField()),
                ("hero_id", models.IntegerField()),
                ("kills", models.IntegerField()),
                ("deaths", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("gold_per_min", models.IntegerField()),
                ("xp_per_min", models.IntegerField()),
                ("last_hits", models.IntegerField()),
                ("denies", models.IntegerField()),
                ("hero_damage", models.IntegerField()),
                ("tower_damage", models.IntegerField()),
                ("hero_healing", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="steam.match",
                    ),
                ),
            ],
            options={
                "unique_together": {("match", "steam_id")},
            },
        ),
    ]
