"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import contextlib
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Add parent directory to Python path for paths module
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import logging

from paths import DEV_DB_PATH, PROD_DB_PATH, TEST_DB_PATH

log = logging.getLogger(__name__)
load_dotenv()
DISCORD_API_BASE_URL = "https://discord.com/api"
SOCIAL_AUTH_DISCORD_KEY = os.environ.get("client_id")
SOCIAL_AUTH_DISCORD_SECRET = os.environ.get("discord_secret")
DISCORD_BOT_TOKEN = os.environ.get("discord_token")
DISCORD_GUILD_ID = 734185035623825559
# SOCIAL_AUTH_LOGIN_REDIRECT_URL= "http://localhost:8000/complete/discord/"
SOCIAL_AUTH_DJANGO_EXTRA_DATA = [
    "avatar",
    "id",
    "global_name",
]
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTRA_DATA = [
    "username",
    "avatar",
    "id",
    "global_name",
]


BASE_DIR_PATH = Path(BASE_DIR)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "v*kswpdyi3+*-=q4a)7&_!xwb%@udm1vi56r690!!j6e*p3^mn"
import logging

# SECURITY WARNING: don't run with debug turned on in production!


def env_bool(key: str, default: bool = False) -> bool:
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


NODE_ENV = "dev"
TEST = env_bool("TEST")
RELEASE = env_bool("RELEASE")
DEBUG = env_bool("DEBUG")

if DEBUG:
    logging.basicConfig(level=logging.DEBUG)
# Application definition
if "NODE_ENV" in os.environ:
    NODE_ENV = os.environ.get("NODE_ENV")
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
    "social_django",
    "rest_framework",
    "django_jinja",
    "corsheaders",
    "steam",
    "bracket",
    "discordbot",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django_jinja.backend.Jinja2",
        "APP_DIRS": False,
        "DIRS": [
            os.path.join(BASE_DIR, "common", "templates"),
        ],
        "OPTIONS": {
            "match_extension": ".html",
            "match_regex": r"^(?!admin/).*",
            "filters": {
                "backend_name": "common.filters.backend_name",
                "backend_class": "common.filters.backend_class",
                "icon_name": "common.filters.icon_name",
                "social_backends": "common.filters.social_backends",
                "legacy_backends": "common.filters.legacy_backends",
                "oauth_backends": "common.filters.oauth_backends",
                "filter_backends": "common.filters.filter_backends",
                "slice_by": "common.filters.slice_by",
            },
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
            ],
        },
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR_PATH / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS = ["dota.kettle.sh", "localhost"]

AUTHENTICATION_BACKENDS = (
    "social_core.backends.discord.DiscordOAuth2",
    "social_core.backends.email.EmailAuth",
    "social_core.backends.username.UsernameAuth",
    "django.contrib.auth.backends.ModelBackend",
)

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/done"
# SOCIAL_AUTH_STRATEGY = "social_django.strategy.DjangoStrategy"
SOCIAL_AUTH_STORAGE = "social_django.models.DjangoStorage"
# SOCIAL_AUTH_STORAGE = 'app.models.CustomDjangoStorage'
SOCIAL_AUTH_GOOGLE_OAUTH_SCOPE = [
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/userinfo.profile",
]
SOCIAL_AUTH_EMAIL_FORM_HTML = "email_signup.html"
SOCIAL_AUTH_EMAIL_VALIDATION_FUNCTION = "app.mail.send_validation"
SOCIAL_AUTH_EMAIL_VALIDATION_URL = "/email-sent/"
SOCIAL_AUTH_USERNAME_FORM_HTML = "username_signup.html"

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    # "common.pipeline.require_email",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.mail.mail_validation",
    "social_core.pipeline.social_auth.associate_by_email",
    "app.pipelines.associate_by_discord_id",
    "app.pipelines.associate_by_discord_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.debug.debug",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "app.pipelines.save_discord",
)

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

db_name = "prod.db.sqlite3"  # Default to prod
match os.environ.get("NODE_ENV", "").lower():
    case "dev":
        db_name = "dev.db.sqlite3"
    case "test":
        db_name = "test.db.sqlite3"
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR_PATH / db_name,
        "OPTIONS": {
            "timeout": 30,  # seconds
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

UserAttributeSimilarityValidator = (  # fix: skip
    "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
)

MinimumLengthValidator = (  # fix: skip
    "django.contrib.auth.password_validation.MinimumLengthValidator"
)

CommonPasswordValidator = (  # fix: skip
    "django.contrib.auth.password_validation.CommonPasswordValidator"
)

NumericPasswordValidator = (  # fix: skip
    "django.contrib.auth.password_validation.NumericPasswordValidator"
)

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": UserAttributeSimilarityValidator,
    },
    {
        "NAME": MinimumLengthValidator,
    },
    {
        "NAME": CommonPasswordValidator,
    },
    {
        "NAME": NumericPasswordValidator,
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

SESSION_COOKIE_SAMESITE = None
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = "/static/"
ALLOWED_HOSTS = ["dota.kettle.sh", "www.dota.kettle.sh", "localhost"]


with contextlib.suppress(ImportError):
    from backend.local_settings import *  # noqa: F403
CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "http://localhost:80",
    "http://localhost:5171",
    "https://localhost:443",
    "https://localhost",
]

CSRF_TRUSTED_ORIGINS = [
    "https://localhost",
    "https://dota.kettle.sh",
    "http://dota.kettle.sh",
    "https://dota.kettle.sh",
    "http://dota.kettle.sh",
    "https://dtx.kettle.sh",
    "http://dtx.kettle.sh",
    "https://kettle.sh",
    "http://kettle.sh",
]
AUTH_USER_MODEL = "app.CustomUser"
