"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import contextlib
import functools
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Add parent directory to Python path for paths module
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import logging
import warnings

from paths import DEV_DB_PATH, PROD_DB_PATH, TEST_DB_PATH

# Show cacheops Redis connection warning only once (not on every import)
warnings.filterwarnings("once", message=r".*cacheops cache is unreachable.*")

log = logging.getLogger(__name__)
load_dotenv()
DISCORD_API_BASE_URL = "https://discord.com/api"
SOCIAL_AUTH_DISCORD_KEY = os.environ.get("client_id")
SOCIAL_AUTH_DISCORD_SECRET = os.environ.get("discord_secret")
DISCORD_BOT_TOKEN = os.environ.get("discord_token")
DISCORD_GUILD_ID = 734185035623825559
DISCORD_ADMIN_CHANNEL_ID = os.environ.get("DISCORD_ADMIN_CHANNEL_ID")
DISCORD_PUBLIC_KEY = os.environ.get("DISCORD_PUBLIC_KEY")
# SOCIAL_AUTH_LOGIN_REDIRECT_URL= "http://localhost:8000/complete/discord/"
SOCIAL_AUTH_DJANGO_EXTRA_DATA = [
    "avatar",
    "id",
    "global_name",
]
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTRA_DATA = [
    "username",
    "avatar",
    "id",
    "global_name",
]


BASE_DIR_PATH = Path(BASE_DIR)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "v*kswpdyi3+*-=q4a)7&_!xwb%@udm1vi56r690!!j6e*p3^mn"

# SECURITY WARNING: don't run with debug turned on in production!


def env_bool(key: str, default: bool = False) -> bool:
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


NODE_ENV = "dev"
TEST = env_bool("TEST")
RELEASE = env_bool("RELEASE")
DEBUG = env_bool("DEBUG")

# Configure logging - default to INFO, allow override via LOG_LEVEL env var
_log_level = os.environ.get("LOG_LEVEL", "INFO").upper()
logging.basicConfig(
    level=getattr(logging, _log_level, logging.INFO),
    format="%(levelname)s:%(name)s:%(message)s",
)

# Quiet down noisy loggers unless explicitly debugging
if _log_level != "DEBUG":
    logging.getLogger("app.models").setLevel(logging.INFO)
    logging.getLogger("app.functions.tournament").setLevel(logging.INFO)


# Application definition
if "NODE_ENV" in os.environ:
    NODE_ENV = os.environ.get("NODE_ENV")

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app.apps.AppConfig",
    "social_django",
    "rest_framework",
    "django_jinja",
    "corsheaders",
    "steam.apps.SteamConfig",
    "bracket.apps.TournamentConfig",
    "discordbot.apps.DiscordbotConfig",
    "cacheops",  # Added for django-cacheops
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "telemetry.middleware.TelemetryMiddleware",  # AFTER AuthenticationMiddleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django_jinja.backend.Jinja2",
        "APP_DIRS": False,
        "DIRS": [
            os.path.join(BASE_DIR, "common", "templates"),
        ],
        "OPTIONS": {
            "match_extension": ".html",
            "match_regex": r"^(?!admin/).*",
            "filters": {
                "backend_name": "common.filters.backend_name",
                "backend_class": "common.filters.backend_class",
                "icon_name": "common.filters.icon_name",
                "social_backends": "common.filters.social_backends",
                "legacy_backends": "common.filters.legacy_backends",
                "oauth_backends": "common.filters.oauth_backends",
                "filter_backends": "common.filters.filter_backends",
                "slice_by": "common.filters.slice_by",
            },
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
            ],
        },
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR_PATH / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"
SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS = ["dota.kettle.sh", "localhost"]

AUTHENTICATION_BACKENDS = (
    "social_core.backends.discord.DiscordOAuth2",
    "social_core.backends.email.EmailAuth",
    "social_core.backends.username.UsernameAuth",
    "django.contrib.auth.backends.ModelBackend",
)

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/done"
# SOCIAL_AUTH_STRATEGY = "social_django.strategy.DjangoStrategy"
SOCIAL_AUTH_STORAGE = "social_django.models.DjangoStorage"
# SOCIAL_AUTH_STORAGE = 'app.models.CustomDjangoStorage'
SOCIAL_AUTH_GOOGLE_OAUTH_SCOPE = [
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/userinfo.profile",
]
SOCIAL_AUTH_EMAIL_FORM_HTML = "email_signup.html"
SOCIAL_AUTH_EMAIL_VALIDATION_FUNCTION = "app.mail.send_validation"
SOCIAL_AUTH_EMAIL_VALIDATION_URL = "/email-sent/"
SOCIAL_AUTH_USERNAME_FORM_HTML = "username_signup.html"

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    # "common.pipeline.require_email",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.mail.mail_validation",
    "social_core.pipeline.social_auth.associate_by_email",
    "app.pipelines.associate_by_discord_id",
    "app.pipelines.associate_by_discord_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.debug.debug",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "app.pipelines.save_discord",
)

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

db_name = "prod.db.sqlite3"  # Default to prod
match os.environ.get("NODE_ENV", "").lower():
    case "dev":
        db_name = "dev.db.sqlite3"
    case "test":
        db_name = "test.db.sqlite3"
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR_PATH / db_name,
        "OPTIONS": {
            "timeout": 30,  # seconds
        },
    }
}


# Docker environment detection
@functools.lru_cache(maxsize=1)
def is_docker() -> bool:
    """Check if running inside Docker container."""
    if os.path.exists("/.dockerenv"):
        return True
    try:
        with open("/proc/1/cgroup", "r") as f:
            return "docker" in f.read()
    except Exception:
        return False


IN_DOCKER = is_docker()
REDIS_HOST = "redis" if IN_DOCKER else "localhost"

# Cacheops/Redis cache configuration
if not env_bool("DISABLE_CACHE"):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"redis://{REDIS_HOST}:6379/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }

CACHEOPS_REDIS = {
    "host": REDIS_HOST,
    "port": 6379,
    "db": 1,
    "socket_timeout": 2,  # Timeout for read/write operations
    "socket_connect_timeout": 2,  # Timeout for initial connection (prevents hanging)
}

# Enable caching for tournament-related models
if not env_bool("DISABLE_CACHE"):
    CACHEOPS = {
        "app.organization": {"ops": "all", "timeout": 60 * 60},
        "app.league": {"ops": "all", "timeout": 60 * 60},
        "app.tournament": {"ops": "all", "timeout": 60 * 60},
        "app.team": {"ops": "all", "timeout": 60 * 60},
        "app.customuser": {"ops": "all", "timeout": 60 * 60},
        "app.draft": {"ops": "all", "timeout": 60 * 60},
        "app.game": {"ops": "all", "timeout": 60 * 60},
        "app.draftround": {"ops": "all", "timeout": 60 * 60},
        # Steam match data - cached with shorter timeout for freshness
        "steam.match": {"ops": "all", "timeout": 30 * 60},
        "steam.playermatchstats": {"ops": "all", "timeout": 30 * 60},
    }
else:
    # Disable all caching - but still register models to avoid ImproperlyConfigured errors
    # when @cached_as is called with model classes
    CACHEOPS = {
        "app.organization": {"ops": (), "timeout": 0},
        "app.league": {"ops": (), "timeout": 0},
        "app.tournament": {"ops": (), "timeout": 0},
        "app.team": {"ops": (), "timeout": 0},
        "app.customuser": {"ops": (), "timeout": 0},
        "app.draft": {"ops": (), "timeout": 0},
        "app.game": {"ops": (), "timeout": 0},
        "app.draftround": {"ops": (), "timeout": 0},
        "steam.match": {"ops": (), "timeout": 0},
        "steam.playermatchstats": {"ops": (), "timeout": 0},
    }


CACHEOPS_DEGRADE_ON_FAILURE = True

# Channel Layers for WebSocket support
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, 6379)],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

UserAttributeSimilarityValidator = (  # fix: skip
    "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
)

MinimumLengthValidator = (  # fix: skip
    "django.contrib.auth.password_validation.MinimumLengthValidator"
)

CommonPasswordValidator = (  # fix: skip
    "django.contrib.auth.password_validation.CommonPasswordValidator"
)

NumericPasswordValidator = (  # fix: skip
    "django.contrib.auth.password_validation.NumericPasswordValidator"
)

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": UserAttributeSimilarityValidator,
    },
    {
        "NAME": MinimumLengthValidator,
    },
    {
        "NAME": CommonPasswordValidator,
    },
    {
        "NAME": NumericPasswordValidator,
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

SESSION_COOKIE_SAMESITE = None
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = "/static/"
ALLOWED_HOSTS = ["dota.kettle.sh", "www.dota.kettle.sh", "localhost"]


with contextlib.suppress(ImportError):
    from backend.local_settings import *  # noqa: F403
CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "http://localhost:80",
    "http://localhost:5171",
    "https://localhost:443",
    "https://localhost",
]

CSRF_TRUSTED_ORIGINS = [
    "https://localhost",
    "https://dota.kettle.sh",
    "http://dota.kettle.sh",
    "https://dota.kettle.sh",
    "http://dota.kettle.sh",
    "https://dtx.kettle.sh",
    "http://dtx.kettle.sh",
    "https://kettle.sh",
    "http://kettle.sh",
]
AUTH_USER_MODEL = "app.CustomUser"

# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", f"redis://{REDIS_HOST}:6379/1")
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", f"redis://{REDIS_HOST}:6379/1"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes

# League Stats Configuration
LEAGUE_MMR_MIN_GAMES = int(os.environ.get("LEAGUE_MMR_MIN_GAMES", "5"))

# League configuration
from config.leagues import app_config

LEAGUE_CHOICES = app_config.league_choices
DEFAULT_LEAGUE_ID = app_config.default_league_id

# =============================================================================
# Telemetry Configuration
# =============================================================================

# Initialize telemetry (structured logging + optional OTel tracing)
from telemetry.config import init_telemetry

init_telemetry()
