# Generated by Django 5.2 on 2026-01-10 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("event", "Discord Event"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("color", models.CharField(max_length=7)),
                ("channel_id", models.CharField(max_length=20)),
                ("include_rsvp", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                ("day_of_week", models.IntegerField(blank=True, null=True)),
                ("time_of_day", models.TimeField(blank=True, null=True)),
                ("next_post_at", models.DateTimeField()),
                (
                    "discord_event_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "discord_message_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_events",
                        to="discordbot.eventtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_user_id", models.CharField(max_length=20)),
                ("discord_username", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("yes", "Attending"),
                            ("maybe", "Maybe"),
                            ("no", "Not Attending"),
                        ],
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="discordbot.scheduledevent",
                    ),
                ),
            ],
            options={
                "unique_together": {("scheduled_event", "discord_user_id")},
            },
        ),
    ]
