# Generated by Django 5.2 on 2025-09-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playermatchstats",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
