# Generated by Django 5.2 on 2026-01-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steam", "0002_alter_playermatchstats_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_id", models.IntegerField(unique=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_match_id", models.BigIntegerField(blank=True, null=True)),
                ("failed_match_ids", models.JSONField(default=list)),
                ("is_syncing", models.BooleanField(default=False)),
            ],
        ),
    ]
