# Generated by Django 5.2 on 2026-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steam", "0004_playermatchstats_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="league_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
