# Generated by Django 5.2 on 2026-01-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_alter_draft_tournament_alter_tournament_winning_team"),
        ("steam", "0005_match_league_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMatchSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("player_overlap", models.IntegerField()),
                ("auto_linked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_suggestions",
                        to="app.game",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_suggestions",
                        to="steam.match",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_suggestions",
                        to="app.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "match")},
            },
        ),
    ]
