# Generated by Django 5.2 on 2026-01-07 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steam", "0006_gamematchsuggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaguePlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_id", models.IntegerField(db_index=True)),
                ("games_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("total_kills", models.IntegerField(default=0)),
                ("total_deaths", models.IntegerField(default=0)),
                ("total_assists", models.IntegerField(default=0)),
                ("total_gpm", models.IntegerField(default=0)),
                ("total_xpm", models.IntegerField(default=0)),
                ("win_rate", models.FloatField(default=0.0)),
                ("avg_kills", models.FloatField(default=0.0)),
                ("avg_deaths", models.FloatField(default=0.0)),
                ("avg_assists", models.FloatField(default=0.0)),
                ("avg_gpm", models.FloatField(default=0.0)),
                ("avg_xpm", models.FloatField(default=0.0)),
                ("mmr_adjustment", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "league_id")},
            },
        ),
    ]
