# Generated by Django 5.2 on 2026-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steam", "0007_leagueplayerstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamematchsuggestion",
            name="suggestion_tier",
            field=models.CharField(
                choices=[
                    ("all_players", "All Players Match"),
                    ("captains_plus", "Both Captains + Some Players"),
                    ("captains_only", "Both Captains Only"),
                    ("partial", "Partial Player Overlap"),
                ],
                default="partial",
                max_length=20,
            ),
        ),
    ]
