# Generated by Django 5.2 on 2025-04-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="discordId",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="discordUsername",
            field=models.TextField(null=True),
        ),
    ]
