# Generated by Django 5.2 on 2025-04-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customuser_avatar_customuser_discordid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="discordId",
            field=models.TextField(null=True),
        ),
    ]
