# Generated by Django 5.2 on 2025-04-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_created_by_customuser_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mmr',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='steamid',
        ),
    ]
