# Generated by Django 5.2 on 2025-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customuser_avatar_remove_customuser_mmr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mmr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='steamid',
            field=models.IntegerField(null=True),
        ),
    ]
