# Generated by Django 5.2 on 2025-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_game_team1_remove_game_team2_game_dire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="discordId",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="steamid",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
