# Generated by Django 5.2 on 2025-04-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dota',
        ),
    ]
