# Generated by Django 5.2 on 2025-07-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_customuser_position_customuser_positions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="teams",
        ),
    ]
