# Generated by Django 5.2 on 2025-07-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_tournament_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="app.tournament",
            ),
        ),
    ]
