# Generated by Django 5.2 on 2025-07-20 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_team_tournament"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="dire",
        ),
        migrations.RemoveField(
            model_name="game",
            name="radiant",
        ),
        migrations.AddField(
            model_name="game",
            name="dire_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_dire",
                to="app.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="gameid",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="radiant_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_radiant",
                to="app.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="app.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="users",
            field=models.ManyToManyField(
                related_name="games", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="winning_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_won",
                to="app.team",
            ),
        ),
        migrations.CreateModel(
            name="GameStat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("hero_damage", models.IntegerField(default=0)),
                ("tower_damage", models.IntegerField(default=0)),
                ("gold_per_minute", models.IntegerField(default=0)),
                ("xp_per_minute", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="app.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
