# Generated by Django 5.2 on 2025-08-02 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_draft_captain_order_team_draft_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="captains",
            field=models.ManyToManyField(
                blank=True,
                related_name="tournaments_as_captain",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
