# Generated by Django 5.2 on 2025-08-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_tournament_captains"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="tournment_type",
            new_name="tournament_type",
        ),
    ]
