# Generated by Django 5.2 on 2025-08-23 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_draft_tournament"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="users",
        ),
        migrations.AddField(
            model_name="gamestat",
            name="radiant",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
