# Generated by Django 5.2 on 2025-09-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_remove_tournamentmatch_tournament_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="latest_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_round",
                to="app.draftround",
            ),
        ),
    ]
