# Generated by Django 5.2 on 2025-09-05 15:17

import django.db.models.deletion
from django.db import migrations, models


def create_default_positions(apps, schema_editor):
    """
    Create a default PositionsModel for each CustomUser that doesn't have one.
    """
    CustomUser = apps.get_model("app", "CustomUser")
    PositionsModel = apps.get_model("app", "PositionsModel")
    for user in CustomUser.objects.filter(positions__isnull=True):
        positions = PositionsModel.objects.create()
        user.positions = positions
        user.save(update_fields=["positions"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_remove_draft_latest_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionsModel",
            fields=[
                # ... fields for PositionsModel
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="positions",
            field=models.ForeignKey(
                help_text="Positions field",
                null=True,  # It will be null=True at this stage
                on_delete=django.db.models.deletion.CASCADE,
                to="app.positionsmodel",
            ),
        ),
        migrations.RunPython(create_default_positions),
        migrations.AlterField(
            model_name="customuser",
            name="positions",
            field=models.ForeignKey(
                null=False,
                help_text="Positions field",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.positionsmodel",
            ),
        ),
    ]
