# Generated by Django 5.2 on 2025-09-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_positionsmodel_carry_positionsmodel_hard_support_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="positions",
            field=models.ForeignKey(
                blank=True,
                help_text="Positions field",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.positionsmodel",
            ),
        ),
    ]
