# Generated by Django 5.2 on 2025-09-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_alter_customuser_positions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="positions",
            field=models.ForeignKey(
                blank=True,
                help_text="Positions field",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.positionsmodel",
            ),
        ),
    ]
