# Generated by Django 5.2 on 2025-09-08 11:54

from django.db import migrations

from django.db import models
import django.db.models.deletion


def create_default_positions(apps, schema_editor):
    """
    Create a default PositionsModel for each CustomUser that doesn't have one.
    """
    CustomUser = apps.get_model("app", "CustomUser")
    PositionsModel = apps.get_model("app", "PositionsModel")
    for user in CustomUser.objects.filter(positions__isnull=True):
        positions = PositionsModel.objects.create()
        user.positions = positions
        user.save(update_fields=["positions"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_alter_customuser_positions"),
    ]

    operations = [
        migrations.RunPython(create_default_positions),
        migrations.AlterField(
            model_name="customuser",
            name="positions",
            field=models.ForeignKey(
                blank=True,
                help_text="Positions field",
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.positionsmodel",
            ),
        ),
    ]
