# Generated by Django 5.2 on 2025-09-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_auto_20250908_1154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams_as_captain",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
