# Generated by Django 5.2 on 2025-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_alter_team_captain"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="draft_style",
            field=models.CharField(
                choices=[("snake", "Snake"), ("normal", "Normal")],
                default="snake",
                help_text="Draft style: snake or normal",
                max_length=10,
            ),
        ),
    ]
