# Generated by Django 5.2 on 2025-09-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_draft_draft_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="tournament",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft",
                to="app.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="winning_team",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments_won",
                to="app.team",
            ),
        ),
    ]
