# Generated by Django 5.2 on 2026-01-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_alter_draft_tournament_alter_tournament_winning_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="bracket_type",
            field=models.CharField(
                choices=[
                    ("winners", "Winners Bracket"),
                    ("losers", "Losers Bracket"),
                    ("grand_finals", "Grand Finals"),
                ],
                default="winners",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="next_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_games",
                to="app.game",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="next_game_slot",
            field=models.CharField(
                blank=True,
                choices=[("radiant", "Radiant"), ("dire", "Dire")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="position",
            field=models.IntegerField(
                default=0, help_text="Position within round (0-indexed)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("live", "Live"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
