# Generated by Django 5.2 on 2026-01-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_add_bracket_fields_to_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="elimination_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Elimination"),
                    ("double", "Double Elimination"),
                    ("swiss", "Swiss"),
                ],
                default="double",
                help_text="single=loser out, double=loser drops to losers bracket, swiss=record-based",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="loser_next_game",
            field=models.ForeignKey(
                blank=True,
                help_text="Game where loser advances to (for double elim rounds)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loser_source_games",
                to="app.game",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="loser_next_game_slot",
            field=models.CharField(
                blank=True,
                choices=[("radiant", "Radiant"), ("dire", "Dire")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="swiss_record_losses",
            field=models.IntegerField(
                default=0, help_text="Team's losses entering this match (Swiss format)"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="swiss_record_wins",
            field=models.IntegerField(
                default=0, help_text="Team's wins entering this match (Swiss format)"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="bracket_type",
            field=models.CharField(
                choices=[
                    ("winners", "Winners Bracket"),
                    ("losers", "Losers Bracket"),
                    ("grand_finals", "Grand Finals"),
                    ("swiss", "Swiss"),
                ],
                default="winners",
                max_length=20,
            ),
        ),
    ]
