# Generated by Django 5.2 on 2026-01-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_add_bracket_config_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="league_mmr",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
