# Generated by Django 5.2 on 2026-01-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_customuser_league_mmr"),
        ("app", "0043_draft_style_shuffle"),
    ]

    operations = []
