# Generated by Django 5.2 on 2026-01-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_merge_20260107_1855"),
        ("app", "0045_draftround_captain_nullable"),
    ]

    operations = []
