# Generated by Django 5.2 on 2026-01-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_merge_20260108_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="placement",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Final tournament placement (1=winner, 2=runner-up, etc.)",
                null=True,
            ),
        ),
    ]
