# Generated by Django 5.2 on 2026-01-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_team_placement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameStat",
        ),
    ]
