# Generated by Django 5.2 on 2026-01-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_remove_gamestat"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="league_id",
            field=models.IntegerField(
                blank=True,
                default=17929,
                help_text="Steam league ID for match linking",
                null=True,
            ),
        ),
    ]
