# Generated by Django 5.2 on 2026-01-13 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_tournament_league_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("draft_started", "Draft Started"),
                            ("draft_completed", "Draft Completed"),
                            ("captain_assigned", "Captain Assigned"),
                            ("player_picked", "Player Picked"),
                            ("tie_roll", "Tie Roll"),
                            ("pick_undone", "Pick Undone"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Event-specific data (JSON)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_events_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.draft",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
