# Generated by Django 5.2 on 2026-01-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_draft_event_model"),
        ("app", "0050_joke"),
    ]

    operations = []
