# Generated by Django 5.2 on 2026-01-17 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_alter_customuser_id_alter_draft_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="dropin_members",
            field=models.ManyToManyField(
                blank=True, related_name="teams_as_dropin", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="left_members",
            field=models.ManyToManyField(
                blank=True, related_name="teams_as_left", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="teams_as_member", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
