# Generated by Django 5.2 on 2026-01-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_add_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_users",
                to="app.organization",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_organization",
                to="app.league",
            ),
        ),
    ]
