# Generated by Django 5.2 on 2026-01-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_add_default_org_league"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="league_id",
            field=models.IntegerField(
                blank=True,
                db_column="league_id",
                default=17929,
                help_text="Steam league ID for match linking",
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="tournament",
            old_name="league_id",
            new_name="steam_league_id",
        ),
        migrations.AddField(
            model_name="tournament",
            name="league",
            field=models.ForeignKey(
                blank=True,
                db_column="league_fk_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="app.league",
            ),
        ),
    ]
