# Generated by Django 5.2 on 2026-01-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_alter_team_dropin_members_alter_team_left_members_and_more"),
        ("app", "0055_migrate_tournament_leagues"),
    ]

    operations = []
