# Generated by Django 5.2 on 2026-01-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_merge_20260117_2333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
