# Generated by Django 5.2 on 2026-01-18 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_alter_league_id_alter_organization_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="app.league",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="app.tournament",
            ),
        ),
    ]
