# Generated by Django 5.2 on 2026-01-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_game_add_league_optional_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Tournament timezone (e.g., 'America/New_York', 'Europe/London')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="date_played",
            field=models.DateTimeField(
                help_text="Tournament date and time (stored in UTC)"
            ),
        ),
    ]
