# Generated by Django 5.2 on 2026-01-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_tournament_datetime_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_first_pick", models.BooleanField(blank=True, null=True)),
                ("is_radiant", models.BooleanField(blank=True, null=True)),
                ("reserve_time_remaining", models.IntegerField(default=90000)),
                ("is_ready", models.BooleanField(default=False)),
                ("is_connected", models.BooleanField(default=False)),
                (
                    "tournament_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_draft_teams",
                        to="app.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeroDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting_for_captains", "Waiting for Captains"),
                            ("rolling", "Rolling"),
                            ("choosing", "Choosing"),
                            ("drafting", "Drafting"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="waiting_for_captains",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="herodraft",
                        to="app.game",
                    ),
                ),
                (
                    "roll_winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_rolls",
                        to="app.draftteam",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="draftteam",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_teams",
                to="app.herodraft",
            ),
        ),
        migrations.CreateModel(
            name="HeroDraftEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("captain_connected", "Captain Connected"),
                            ("captain_disconnected", "Captain Disconnected"),
                            ("draft_paused", "Draft Paused"),
                            ("draft_resumed", "Draft Resumed"),
                            ("roll_triggered", "Roll Triggered"),
                            ("roll_result", "Roll Result"),
                            ("choice_made", "Choice Made"),
                            ("round_started", "Round Started"),
                            ("hero_selected", "Hero Selected"),
                            ("round_timeout", "Round Timeout"),
                            ("draft_completed", "Draft Completed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.herodraft",
                    ),
                ),
                (
                    "draft_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="app.draftteam",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroDraftRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[("ban", "Ban"), ("pick", "Pick")], max_length=8
                    ),
                ),
                ("hero_id", models.IntegerField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("grace_time_ms", models.IntegerField(default=30000)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="app.herodraft",
                    ),
                ),
                (
                    "draft_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="app.draftteam",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number"],
            },
        ),
    ]
