# Generated by Django 5.2 on 2026-01-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_herodraft_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herodraft",
            name="state",
            field=models.CharField(
                choices=[
                    ("waiting_for_captains", "Waiting for Captains"),
                    ("rolling", "Rolling"),
                    ("choosing", "Choosing"),
                    ("drafting", "Drafting"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="waiting_for_captains",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="herodraftevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("captain_connected", "Captain Connected"),
                    ("captain_disconnected", "Captain Disconnected"),
                    ("captain_ready", "Captain Ready"),
                    ("draft_paused", "Draft Paused"),
                    ("draft_resumed", "Draft Resumed"),
                    ("roll_triggered", "Roll Triggered"),
                    ("roll_result", "Roll Result"),
                    ("choice_made", "Choice Made"),
                    ("round_started", "Round Started"),
                    ("hero_selected", "Hero Selected"),
                    ("round_timeout", "Round Timeout"),
                    ("draft_completed", "Draft Completed"),
                ],
                max_length=32,
            ),
        ),
    ]
