# Generated by Django 5.2 on 2026-01-21 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_alter_herodraft_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="age_decay_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable age-based decay for older matches"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="age_decay_half_life_days",
            field=models.PositiveIntegerField(
                default=180, help_text="Half-life in days for age decay calculation"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="age_decay_minimum",
            field=models.FloatField(
                default=0.1, help_text="Minimum decay factor (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="fixed_delta",
            field=models.FloatField(
                default=25.0,
                help_text="Fixed rating change per game (for fixed_delta system)",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="k_factor_default",
            field=models.FloatField(
                default=32.0, help_text="Default K-factor for Elo calculations"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="k_factor_placement",
            field=models.FloatField(
                default=64.0, help_text="K-factor for players in placement games"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="placement_games",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Number of placement games before using default K-factor",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="rating_system",
            field=models.CharField(
                choices=[("elo", "Elo"), ("fixed_delta", "Fixed Delta")],
                default="elo",
                help_text="Rating calculation method",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="recalc_max_age_days",
            field=models.PositiveIntegerField(
                default=90, help_text="Maximum age in days for match recalculation"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="recalc_mmr_threshold",
            field=models.PositiveIntegerField(
                default=500, help_text="Maximum MMR change allowed for recalculation"
            ),
        ),
        migrations.CreateModel(
            name="LeagueMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "played_at",
                    models.DateTimeField(help_text="When the match was played"),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tournament stage (e.g., 'quarterfinal', 'grand_final')",
                        max_length=64,
                    ),
                ),
                (
                    "bracket_slot",
                    models.CharField(
                        blank=True,
                        help_text="Bracket position identifier",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False, help_text="Whether ratings have been calculated"
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, help_text="When ratings were calculated", null=True
                    ),
                ),
                (
                    "recalculation_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this match has been recalculated",
                    ),
                ),
                (
                    "last_recalculated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When ratings were last recalculated",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to Game model if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="league_match",
                        to="app.game",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="app.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Match",
                "verbose_name_plural": "League Matches",
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="LeagueRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_mmr",
                    models.IntegerField(
                        default=0, help_text="Player's MMR when joining the league"
                    ),
                ),
                (
                    "positive_stats",
                    models.FloatField(
                        default=0.0,
                        help_text="Accumulated positive rating changes (wins)",
                    ),
                ),
                (
                    "negative_stats",
                    models.FloatField(
                        default=0.0,
                        help_text="Accumulated negative rating changes (losses)",
                    ),
                ),
                (
                    "rating_deviation",
                    models.FloatField(
                        default=350.0,
                        help_text="Rating deviation (uncertainty) for Glicko-2",
                    ),
                ),
                (
                    "volatility",
                    models.FloatField(
                        default=0.06, help_text="Volatility for Glicko-2"
                    ),
                ),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("last_played", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="app.league",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "League Rating",
                "verbose_name_plural": "League Ratings",
                "ordering": ["-positive_stats", "negative_stats"],
                "unique_together": {("league", "player")},
            },
        ),
        migrations.CreateModel(
            name="LeagueMatchParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_side",
                    models.CharField(
                        choices=[("radiant", "Radiant"), ("dire", "Dire")], max_length=8
                    ),
                ),
                (
                    "mmr_at_match",
                    models.IntegerField(help_text="Player's base MMR at time of match"),
                ),
                (
                    "elo_before",
                    models.FloatField(help_text="Player's total Elo before this match"),
                ),
                (
                    "elo_after",
                    models.FloatField(help_text="Player's total Elo after this match"),
                ),
                (
                    "k_factor_used",
                    models.FloatField(help_text="K-factor used in calculation"),
                ),
                (
                    "rating_deviation_used",
                    models.FloatField(
                        default=350.0,
                        help_text="Rating deviation at time of calculation",
                    ),
                ),
                (
                    "age_decay_factor",
                    models.FloatField(
                        default=1.0,
                        help_text="Age decay factor applied (1.0 = no decay)",
                    ),
                ),
                ("is_winner", models.BooleanField()),
                ("delta", models.FloatField(help_text="Rating change from this match")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="app.leaguematch",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_match_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_participations",
                        to="app.leaguerating",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Match Participant",
                "verbose_name_plural": "League Match Participants",
                "ordering": ["team_side", "player__username"],
                "unique_together": {("match", "player")},
            },
        ),
    ]
