# Generated by Django 5.2 on 2026-01-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_league_rating_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dota_mmr_last_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_active_dota_mmr",
            field=models.BooleanField(default=False),
        ),
    ]
