# Generated by Django 5.2 on 2026-01-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_customuser_mmr_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="discord_link",
            field=models.URLField(blank=True, default=""),
        ),
    ]
