# Generated by Django 5.2 on 2026-01-24 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_add_organization_discord_link"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add_admin", "Add Admin"),
                            ("remove_admin", "Remove Admin"),
                            ("add_staff", "Add Staff"),
                            ("remove_staff", "Remove Staff"),
                            ("link_organization", "Link Organization"),
                            ("unlink_organization", "Unlink Organization"),
                            ("create", "Create League"),
                            ("update", "Update League"),
                            ("delete", "Delete League"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "League Log",
                "verbose_name_plural": "League Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrgLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add_admin", "Add Admin"),
                            ("remove_admin", "Remove Admin"),
                            ("add_staff", "Add Staff"),
                            ("remove_staff", "Remove Staff"),
                            ("transfer_ownership", "Transfer Ownership"),
                            ("create", "Create Organization"),
                            ("update", "Update Organization"),
                            ("delete", "Delete Organization"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Organization Log",
                "verbose_name_plural": "Organization Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AddField(
            model_name="league",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, related_name="leagues", to="app.organization"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="league",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leagues_legacy",
                to="app.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["discordNickname"], name="app_customu_discord_667c90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["guildNickname"], name="app_customu_guildNi_602cf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["discordUsername"], name="app_customu_discord_9497ac_idx"
            ),
        ),
        migrations.AddField(
            model_name="leaguelog",
            name="actor",
            field=models.ForeignKey(
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="league_actions_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaguelog",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="app.league",
            ),
        ),
        migrations.AddField(
            model_name="leaguelog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User affected by the action (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="league_actions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orglog",
            name="actor",
            field=models.ForeignKey(
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_actions_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orglog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="app.organization",
            ),
        ),
        migrations.AddField(
            model_name="orglog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User affected by the action (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_actions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="leaguelog",
            index=models.Index(
                fields=["league", "-created_at"], name="app_leaguel_league__800628_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orglog",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="app_orglog_organiz_b8ea3f_idx",
            ),
        ),
    ]
