# Generated by Django 5.2 on 2026-01-24
"""
Data migration for admin team management:
1. Set first admin as owner for each organization
2. Copy League.organization FK to League.organizations M2M
3. Move orphan tournaments to first organization
"""

from django.db import migrations


def migrate_org_owners(apps, schema_editor):
    """Set first admin as owner for each organization."""
    Organization = apps.get_model("app", "Organization")

    for org in Organization.objects.all():
        # Get first admin
        first_admin = org.admins.first()
        if first_admin:
            org.owner = first_admin
            org.save(update_fields=["owner"])


def migrate_league_organizations(apps, schema_editor):
    """Copy League.organization FK to League.organizations M2M."""
    League = apps.get_model("app", "League")

    for league in League.objects.all():
        if league.organization_id:
            league.organizations.add(league.organization_id)


def migrate_orphan_tournaments(apps, schema_editor):
    """Move tournaments without a league to first organization's first league."""
    Tournament = apps.get_model("app", "Tournament")
    Organization = apps.get_model("app", "Organization")
    League = apps.get_model("app", "League")

    # Get first organization
    first_org = Organization.objects.first()
    if not first_org:
        return  # No organizations, nothing to do

    # Get or create a league for orphan tournaments
    first_league = League.objects.filter(organization=first_org).first()
    if not first_league:
        # Check if any league exists at all
        first_league = League.objects.first()

    if not first_league:
        return  # No leagues exist, can't migrate

    # Find orphan tournaments (no league)
    orphan_tournaments = Tournament.objects.filter(league__isnull=True)
    count = orphan_tournaments.update(league=first_league)
    if count:
        print(f"Migrated {count} orphan tournaments to league: {first_league.name}")


def reverse_migrate_org_owners(apps, schema_editor):
    """Clear owners (reverse migration)."""
    Organization = apps.get_model("app", "Organization")
    Organization.objects.update(owner=None)


def reverse_migrate_league_organizations(apps, schema_editor):
    """Clear M2M relationships (reverse migration)."""
    League = apps.get_model("app", "League")
    for league in League.objects.all():
        league.organizations.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_admin_team_add_fields"),
    ]

    operations = [
        migrations.RunPython(
            migrate_org_owners,
            reverse_migrate_org_owners,
        ),
        migrations.RunPython(
            migrate_league_organizations,
            reverse_migrate_league_organizations,
        ),
        migrations.RunPython(
            migrate_orphan_tournaments,
            migrations.RunPython.noop,  # No reverse for this
        ),
    ]
