# Generated by Django 5.2 on 2026-01-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_admin_team_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="organization",
        ),
    ]
