# Generated by Django 5.2 on 2026-01-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_admin_team_remove_legacy_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["tournament"], name="app_game_tournam_ebb2c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["league"], name="app_game_league__9d936f_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["status"], name="app_game_status_635436_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["gameid"], name="app_game_gameid_71ac99_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["radiant_team"], name="app_game_radiant_aa1c7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["dire_team"], name="app_game_dire_te_715044_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="league",
            index=models.Index(fields=["name"], name="app_league_name_844732_idx"),
        ),
        migrations.AddIndex(
            model_name="league",
            index=models.Index(
                fields=["created_at"], name="app_league_created_a10ab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["created_at"], name="app_organiz_created_557442_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["tournament"], name="app_team_tournam_97ad87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["name"], name="app_team_name_d8f293_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["captain"], name="app_team_captain_5fcdd6_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["name"], name="app_tournam_name_8e0538_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["-date_played"], name="app_tournam_date_pl_35179a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["state"], name="app_tournam_state_18ca9a_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["league"], name="app_tournam_league__8406ee_idx"
            ),
        ),
    ]
