# Generated by Django 5.2 on 2026-01-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0068_add_homepage_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="timezone",
            field=models.CharField(default="America/New_York", max_length=50),
        ),
        migrations.AddField(
            model_name="organization",
            name="timezone",
            field=models.CharField(default="America/New_York", max_length=50),
        ),
    ]
