# Generated by Django 5.2 on 2026-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_add_timezone_to_org_and_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="steam_account_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="steamid",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
