# Generated by Django 5.2 on 2026-01-26 15:19

from django.db import migrations


def relink_users_to_match_stats(apps, schema_editor):
    """
    Re-link PlayerMatchStats records to CustomUser based on steam_id.
    This runs after steamid field is changed to BigIntegerField.
    """
    CustomUser = apps.get_model("app", "CustomUser")
    PlayerMatchStats = apps.get_model("steam", "PlayerMatchStats")

    # Build a map of steam_id -> user for quick lookup
    user_by_steamid = {}
    for user in CustomUser.objects.filter(steamid__isnull=False).exclude(steamid=0):
        user_by_steamid[user.steamid] = user

    # Find unlinked stats and link them
    linked_count = 0
    unlinked_stats = PlayerMatchStats.objects.filter(user__isnull=True)

    for stats in unlinked_stats:
        if stats.steam_id in user_by_steamid:
            stats.user = user_by_steamid[stats.steam_id]
            stats.save(update_fields=["user"])
            linked_count += 1

    if linked_count > 0:
        print(f"  Relinked {linked_count} PlayerMatchStats to users")


def reverse_relink(apps, schema_editor):
    """Reverse migration - no-op since we don't want to unlink users."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_change_steamid_to_biginteger"),
        ("steam", "0001_initial"),  # Ensure steam app migrations have run
    ]

    operations = [
        migrations.RunPython(relink_users_to_match_stats, reverse_relink),
    ]
