# Generated by Django 5.2 on 2026-01-26

from django.db import migrations

STEAM_ID_64_BASE = 76561197960265728


def populate_steam_account_id_and_relink(apps, schema_editor):
    """
    1. Calculate steam_account_id for all users with steamid
    2. Re-link PlayerMatchStats to users based on steam_id matching steamid
    """
    CustomUser = apps.get_model("app", "CustomUser")
    PlayerMatchStats = apps.get_model("steam", "PlayerMatchStats")

    # Step 1: Populate steam_account_id for all users with steamid
    users_updated = 0
    for user in CustomUser.objects.filter(steamid__isnull=False).exclude(steamid=0):
        user.steam_account_id = user.steamid - STEAM_ID_64_BASE
        user.save(update_fields=["steam_account_id"])
        users_updated += 1

    if users_updated > 0:
        print(f"  Populated steam_account_id for {users_updated} users")

    # Step 2: Build a map of steam_id (64-bit) -> user for quick lookup
    user_by_steamid = {}
    for user in CustomUser.objects.filter(steamid__isnull=False).exclude(steamid=0):
        user_by_steamid[user.steamid] = user

    # Step 3: Find unlinked stats and link them
    linked_count = 0
    unlinked_stats = PlayerMatchStats.objects.filter(user__isnull=True)

    for stats in unlinked_stats:
        if stats.steam_id in user_by_steamid:
            stats.user = user_by_steamid[stats.steam_id]
            stats.save(update_fields=["user"])
            linked_count += 1

    if linked_count > 0:
        print(f"  Relinked {linked_count} PlayerMatchStats to users")


def reverse_migration(apps, schema_editor):
    """Reverse migration - clear steam_account_id but don't unlink users."""
    CustomUser = apps.get_model("app", "CustomUser")
    CustomUser.objects.update(steam_account_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_add_steam_account_id"),
        ("steam", "0004_playermatchstats_user"),  # user field added in 0004
    ]

    operations = [
        migrations.RunPython(populate_steam_account_id_and_relink, reverse_migration),
    ]
