# Generated by Django 5.2 on 2026-01-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_populate_steam_account_id_and_relink"),
    ]

    operations = [
        migrations.AddField(
            model_name="herodraft",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
