# Generated by Django 5.2 on 2026-01-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_relink_users_to_match_stats"),
        ("app", "0072_herodraft_paused_at"),
    ]

    operations = []
