# Generated by Django 5.2 on 2026-01-29 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_merge_20260126_1938"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="deputy_captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Next in line for captain if captain is removed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams_as_deputy_captain",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["deputy_captain"], name="app_team_deputy__d95afa_idx"
            ),
        ),
    ]
