# Generated by Django 5.2 on 2026-01-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_add_deputy_captain"),
    ]

    operations = [
        migrations.AddField(
            model_name="herodraft",
            name="resuming_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="herodraft",
            name="state",
            field=models.CharField(
                choices=[
                    ("waiting_for_captains", "Waiting for Captains"),
                    ("rolling", "Rolling"),
                    ("choosing", "Choosing"),
                    ("drafting", "Drafting"),
                    ("paused", "Paused"),
                    ("resuming", "Resuming"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="waiting_for_captains",
                max_length=32,
            ),
        ),
    ]
