# Generated by Django 5.2 on 2026-01-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_add_herodraft_resuming_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="herodraft",
            name="is_manual_pause",
            field=models.BooleanField(default=False),
        ),
    ]
