# Generated by Django 5.2 on 2026-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_add_herodraft_is_manual_pause"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="discord_server_id",
            field=models.CharField(
                blank=True,
                help_text="Discord server (guild) ID for fetching members",
                max_length=20,
                null=True,
            ),
        ),
    ]
